// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWgdbHG7tbaIMoPgQ0Oo7cTEO8yyX7tU',
    appId: '1:712922432471:web:2f7cc385a33a11ca980192',
    messagingSenderId: '712922432471',
    projectId: 'kca-university-foundation',
    authDomain: 'kca-university-foundation.firebaseapp.com',
    storageBucket: 'kca-university-foundation.firebasestorage.app',
    measurementId: 'G-RGEHZVX5ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwYWrPOaXQQ1iVZ0D0Map4PqHHmvd0ExA',
    appId: '1:712922432471:android:738050840fdcb871980192',
    messagingSenderId: '712922432471',
    projectId: 'kca-university-foundation',
    storageBucket: 'kca-university-foundation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBar15OygfK28Ih1v5LtKNf6lfRu2fqaWo',
    appId: '1:712922432471:ios:93eb0dc69d575102980192',
    messagingSenderId: '712922432471',
    projectId: 'kca-university-foundation',
    storageBucket: 'kca-university-foundation.firebasestorage.app',
    iosBundleId: 'com.kca.foundation.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBar15OygfK28Ih1v5LtKNf6lfRu2fqaWo',
    appId: '1:712922432471:ios:93eb0dc69d575102980192',
    messagingSenderId: '712922432471',
    projectId: 'kca-university-foundation',
    storageBucket: 'kca-university-foundation.firebasestorage.app',
    iosBundleId: 'com.kca.foundation.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoWgdbHG7tbaIMoPgQ0Oo7cTEO8yyX7tU',
    appId: '1:712922432471:web:ac1a7b9050c47c71980192',
    messagingSenderId: '712922432471',
    projectId: 'kca-university-foundation',
    authDomain: 'kca-university-foundation.firebaseapp.com',
    storageBucket: 'kca-university-foundation.firebasestorage.app',
    measurementId: 'G-PPXM8H5RH8',
  );
}
